### ISSUE TITLE
希望能给Miku Kernel添加KernelSU

### ISSUE THREAD

**Issue by xmb505** [xiaoleGun/kernel_huawei_kirin970#2]
非常好内核，爱来自瓷器。
啊啊啊啊啊啊啊啊啊啊，我的环境里面总是编译不了，不是哪个文件报错就是路径不对，反正就是编译不上
求求惹qwq，我的编译环境是ubuntu2204，python3.10，gcc用的是git自带的
qwqwqwqwqwqwqwqwqwq

下面是一些报错

find lcdkit hisi folder, include it now!
  Using .. as source for kernel
  CHK     include/generated/timeconst.h
  CHK     include/generated/bounds.h
  CHK     include/generated/asm-offsets.h
  CALL    ../scripts/checksyscalls.sh
-- KernelSU version: 11210
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: 0xb0b91415
  VDSOL   arch/arm64/kernel/vdso/vdso.so.dbg
real-aarch64-linux-android-gcc: fatal error: -fuse-linker-plugin, but liblto_plugin.so not found
compilation terminated.
make[2]: *** [../arch/arm64/kernel/vdso/Makefile:35：arch/arm64/kernel/vdso/vdso.so.dbg] 错误 1
make[1]: *** [arch/arm64/Makefile:177：vdso_prepare] 错误 2
make[1]: 离开目录“/opt/sourcecode/kernel_huawei_kirin970/out”
make: *** [Makefile:152：sub-make] 错误 2

————————————————————————————————————

  Using .. as source for kernel
  HOSTLD  scripts/dtc/dtc
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
  CC      scripts/mod/empty.o
collect2: error: ld returned 1 exit status
make[3]: *** [scripts/Makefile.host:110：scripts/dtc/dtc] 错误 1
make[2]: *** [../scripts/Makefile.build:690：scripts/dtc] 错误 2
make[2]: *** 正在等待未完成的任务....
  CC      scripts/mod/devicetable-offsets.s
  MKELF   scripts/mod/elfconfig.h
  HOSTCC  scripts/mod/modpost.o
  CHK     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/sumversion.o
  HOSTCC  scripts/mod/file2alias.o
-- KernelSU version: 11210
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: 0xb0b91415
  CC      kernel/bounds.s
  CHK     include/generated/timeconst.h
  CHK     include/generated/bounds.h
  CC      arch/arm64/kernel/asm-offsets.s
  HOSTLD  scripts/mod/modpost
make[1]: *** [/opt/sourcecode/kernel_huawei_kirin970/Makefile:627：scripts] 错误 2
make[1]: *** 正在等待未完成的任务....
  CHK     include/generated/asm-offsets.h
  CALL    ../scripts/checksyscalls.sh
make[1]: 离开目录“/opt/sourcecode/kernel_huawei_kirin970/out”
make: *** [Makefile:152：sub-make] 错误 2

**Comment by xmb505** [comment]
啊，走眼了，又整了半天原来发现还有另一个项目啊awa

**Comment by xmb505** [comment]
但是源码还是无法编译qwq，我fork了一个仓库，然后编译，就报错了ww

real-aarch64-linux-android-gcc: fatal error: -fuse-linker-plugin, but liblto_plugin.so not found
compilation terminated.
make[2]: *** [../arch/arm64/kernel/vdso/Makefile:35: arch/arm64/kernel/vdso/vdso.so.dbg] Error 1
make[1]: *** [arch/arm64/Makefile:177: vdso_prepare] Error 2
make[1]: Leaving directory '/home/runner/work/miku_kernel_for_su/miku_kernel_for_su/out'
make: *** [Makefile:152: sub-make] Error 2

**Comment by xiaoleGun** [comment]
手机飞升了
